# docker-compose.yml
# Defines services for Frontend (Nginx), Backend (Flask), and Database (Postgres).
# Uses Git repositories for build contexts, suitable for Portainer deployment without direct file access.

version: '3.8'

services:
  # Frontend Nginx Service
  frontend:
    build:
      # context: ./frontend # Context is now implied to be '.' relative to compose file, targeting frontend dir
      dockerfile: ./frontend/Dockerfile # Path relative to compose file
    container_name: openscad_frontend
    restart: unless-stopped
    ports:
      - "8080:80" # Map host port 8080 to Nginx container port 80
    networks:
      - openscad_network
    depends_on:
      - backend # Optional: wait for backend (though frontend is static)

  # Backend Flask Service
  backend:
    build:
      # context: ./backend # Context is now implied to be '.' relative to compose file, targeting backend dir
      dockerfile: ./backend/Dockerfile # Path relative to compose file
    container_name: openscad_backend
    restart: unless-stopped
    ports:
      - "5000:5000" # Map host port 5000 to container port 5000
    environment:
      # Use environment variables defined via .env file or system environment
      - DATABASE_URL=postgresql://\${POSTGRES_USER}:\${POSTGRES_PASSWORD}@db:5432/\${POSTGRES_DB} # Escaped $ for compose variables
      - FLASK_APP=backend_server.py
      - FLASK_ENV=development # Change to 'production' for production
      # Add other backend environment variables if needed
    volumes:
      # Mount local code for development (reflects changes without rebuilding)
      # Remove this if you prefer builds to copy code permanently
      - ./backend:/app
    depends_on:
      - db
    networks:
      - openscad_network

  # PostgreSQL Database Service
  db:
    image: postgres:15
    container_name: openscad_db
    restart: unless-stopped
    environment:
      # Use environment variables defined via .env file or system environment
      POSTGRES_USER: \${POSTGRES_USER:-openscad_user} # Escaped $
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:-supersecretpassword} # Escaped $
      POSTGRES_DB: \${POSTGRES_DB:-openscad_examples} # Escaped $
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      # Optionally expose DB port (use with caution)
      - "5432:5432"
    networks:
      - openscad_network

# Define named volumes
volumes:
  pgdata:

# Define custom network
networks:
  openscad_network:
    driver: bridge
